---
- name: Install and set maven
  hosts: maven-srv
  become: yes

  tasks:
  - name: Ensure maven packages are present
    apt:
      name: maven
      state: present

  - name: Ensure boxfuse-project from repository
    git:
      repo: clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /usr/share/maven

  - name: Ensure maven package
    shell:  cd /usr/share/maven/boxfuse-sample-java-war-hello && mvn package

- name: Install and set tomcat
  hosts: tomcat-srv
  become: yes

