---
- name: Install and set maven
  hosts: maven-srv
  become: yes

  tasks:
  - name: Ensure maven packages are present
    apt:
      name: maven
      state: present

  - name: Clone boxfuse-project from repository
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /usr/share/maven
      clone: yes
      update: yes

  - name: Ensure maven package
    shell:  cd /usr/share/maven/boxfuse-sample-java-war-hello && mvn package

- name: Install and set tomcat
  hosts: tomcat-srv
  become: yes

  tasks:
  - name: Ensure tomcat packages are present
    apt:
      name: tomcat
      state: present

  - name: Ensure maven artifact to tomcat
    copy:
      src: root@192.168.99.112:/usr/share/maven/target
      dest: root@192.168.99.113:/usr/local/tomcat/webapps

  - name: Ensure tomcat service is started
    service:
      name: tomcat
      state: started