---
- name: Install and set maven
  hosts: maven-srv
  become: yes

  tasks:
  - name: Ensure maven packages are present
    apt:
      name: maven
      state: present

  - name: Clone boxfuse-project from repository
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /usr/share/maven/boxfuse-sample-java-war-hello
      clone: yes
      update: yes

  - name: Ensure maven package
    shell:  cd /usr/share/maven/boxfuse-sample-java-war-hello && mvn package

- name: Install and set tomcat
  hosts: tomcat-srv
  become: yes

  tasks:
  - name: Ensure tomcat packages are present
    apt:
      name: tomcat9
      state: present

  - name: Transfer maven artifact from maven-srv to tomcat-srv
    synchronize:
      src: /usr/share/maven/boxfuse-sample-java-war-hello/target
      dest: /var/lib/tomcat9/webapps
#    delegate_to: "{{ groups['web'][0] }}"
    delegate_to: "{{ item }}"
    delegate_facts: true
    loop: "{{ groups['web'] }}"

  - name: Ensure tomcat service is restarted
    service:
      name: tomcat9
      state: restarted