- name: Install and set tomcat
  hosts: tomcat-srv
  become: yes

  tasks:
  - name: Transfer maven artifact from maven-srv to tomcat-srv
    synchronize:
#      mode: pull
      src: /usr/share/maven/boxfuse-sample-java-war-hello/target/
      dest: /var/lib/tomcat9/webapps
    delegate_to: 192.168.99.112