- name: Install and set tomcat
  hosts: tomcat-srv
  become: yes

  tasks:
  - name: Transfer maven artifact from maven-srv to tomcat-srv
    synchronize:
#      mode: pull
      src: /usr/share/maven/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /usr/local/tomcat/webapps/
    delegate_to: root@192.168.99.112