---
# tasks file for prod
- name: Ensure tomcat packages are present
  apt:
    name: tomcat9
    state: present

- name: Transfer maven artifact from maven-srv to tomcat-srv
  synchronize:
    src: {{ src_build }}
    dest: {{ dest_prod }}
  delegate_to: 192.168.99.112