---
# tasks file for prod
- name: Ensure tomcat packages are present
  apt:
    name: tomcat9
    state: present

- name: Transfer maven artifact from maven-srv to tomcat-srv
  synchronize:
    src: "{{ src_build }}"
    dest: "{{ dest_prod }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['web'] }}"

- name: Ensure tomcat service is restarted
  service:
    name: tomcat9
    state: restarted